### ISSUE TITLE
 edit.py asks - Is DaVinci Resolve open? even if Davinci Resolve 18 is open.

### ISSUE THREAD

**Issue by arunshekher** [tonyflo/videoflo#2]
edit.py outputs the message -  "Is DaVinci Resolve open?" even if Davinci Resolve 18 is open and running.

```
(vf) ➜  videoflo git:(main) ✗ python edit.py my-first-video -c pl
Is DaVinci Resolve open?
```

macOS 12.5
Python 3.10.6
Davinci Resolve 18.0.3 Build 5

**Comment by tonyflo** [comment]
Are you using DaVinci Resolve Studio (the paid version)? The free version of DaVinci does not have access to the API/scripting features.

**Comment by arunshekher** [comment]
I am using the free version. Sorry I didn't know about that, I am new to Davinci Resolve as well. Thanks for your time.
